---
- hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Install python3-apt
      ansible.builtin.apt:
        name: python3-apt
        state: present
        update_cache: yes

    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present

    - name: Copy Apache config file
      ansible.builtin.copy:
        src: files/config/apache.conf
        dest: /etc/apache2/apache2.conf
        owner: root
        group: root
        mode: '0644'

    - name: Copy index.html file
      ansible.builtin.copy:
        src: files/site/index.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'

    - name: Enable Apache headers module
      ansible.builtin.file:
        src: /etc/apache2/mods-available/headers.load
        dest: /etc/apache2/mods-enabled/headers.load
        state: link
        owner: root
        group: root

    - name: Restart apache2 service
      ansible.builtin.service:
        name: apache2
        state: restarted
